## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
## Playbook Assumptions:
##

---
- hosts: localhost
  connection: local

  tasks:

  - name: "DEPLOYER-COCKPIT: install cockpit packages"
    yum: name=cockpit,cockpit-dashboard,cockpit-machines state=installed

  - name: "DEPLOYER-COCKPIT: create cockpit systemd drop-in directory"
    file:
      path: "/etc/systemd/system/cockpit.socket.d/"
      mode: "0755"
      owner: "root"
      group: "root"
      state: directory

  - name: "DEPLOYER-COCKPIT: deploy cockpit configuration"
    vars:
      - p_port: "{{ deployer_cfg.cockpit_port }}"
    template:
      src:  "cockpit-listen-conf.j2"
      dest: "/etc/systemd/system/cockpit.socket.d/listen.conf"
      owner: root
      group: root
      mode: 0644

  - name: "DEPLOYER-COCKPIT: enable system services"
    service: name="{{ item }}" state=restarted enabled=yes masked=no
    with_items:
      - "cockpit"
      - "cockpit.socket"

  - name: "DEPLOYER-COCKPIT: add firewalld services"
    firewalld:
      service: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
      - "cockpit"

  - name: "DEPLOYER-COCKPIT: add firewalld ports"
    firewalld:
      port: "{{ item }}"
      immediate: yes
      permanent: yes
      state: enabled
    with_items:
      - "{{ deployer_cfg.cockpit_port }}/tcp"

# A reminder that if we use a port not natively included by selinux, we need to add it
#   
#  - name: "DEPLOYER-COCKPIT: add cockpit port to selinux http_port_t"
#  - shell:
#      cmd: |
#        semanage port -a -t http_port_t -p tcp {{ deployer_cfg.cockpit_port }}
