########################################
##
## Reference
##
##   https://www.linuxtechi.com/enable-nested-virtualization-kvm-centos-7-rhel-7/

---
- hosts: myVirthost
  tasks:

########################################
##
## Test for hardware compatability
##

  - name: "LIBVIRT-NESTED-VIRT: does hardware support AMD or INTEL virt"
    shell:
      cmd: |
        if grep -q 'vmx' /proc/cpuinfo ; then
          echo "intel"
        elif grep -q 'svm' /proc/cpuinfo ; then
          echo "amd"
        else
          exit 1
        fi
    register: test_virt

########################################
##
## cat /sys/module/kvm_{intel|amd}/parameters/nested
## 

  - name: "LIBVIRT-NESTED-VIRT: check if nested virt enabled"
    when: test_virt.rc == 0
    shell:
      cmd: 
        grep -q 'Y\|1' /sys/module/kvm_{{ test_virt.stdout }}/parameters/nested
    ignore_errors: yes
    register: test_nestedvirt

########################################
##
## Deploy configuration template
##

  - name: "LIBVIRT-NESTED-VIRT: deploy config template"
    when: test_nestedvirt.rc != 0
    template:
      src:  nested-virt-{{ test_virt.stdout }}.j2
      dest: /etc/modprobe.d/kvm-nested.conf
      mode: 0644

########################################
##
## Reload the kernel module
##

  - name: "LIBVIRT-NESTED-VIRT: stop libvirtd service"
    when: test_nestedvirt.rc != 0
    service:
      name: libvirtd
      state: stopped

  - name: "LIBVIRT-NESTED-VIRT: reload kvm kernel module"
    when: test_nestedvirt.rc != 0
    shell:
      cmd: |
        modprobe -r kvm_{{ test_virt.stdout }}
        sleep 3
        modprobe -a kvm_{{ test_virt.stdout }}

  - name: "LIBVIRT-NESTED-VIRT: start libvirtd service"
    when: test_nestedvirt.rc != 0
    service:
      name: libvirtd
      state: started

########################################
##
## FIN!
##

