## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##
##

---
- hosts: myVirthost
  tasks:

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_libvirt }}"

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_rs_profiles }}"

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_hw_profiles }}"

  - debug:
      var: kvm_cfg

  - debug:
      var: rs_profile[hostvars[item]['h_rsPROF']]
    loop: "{{ groups['myNodes'] }}"

  - debug:
      var: hw_profile[hostvars[item]['h_hwPROF']]
    loop: "{{ groups['myNodes'] }}"

  - name: "LIBVIRT-CREATE-NODE: deploy kickstart configuration"
    vars:
      - p_diskDevice: "{{ hw_profile[hostvars[item]['h_hwPROF']].disk.dev }}"
    template:
      src: "ks-baseos.j2"
      dest: "/var/www/html/ks.cfg"
      owner: root
      group: apache
      mode: 0644
    loop: "{{ groups['myNodes'] }}"

  - name: "LIBVIRT-CREATE-NODE: virt-install node"
    vars:
      p_name:     "{{ hostvars[item]['inventory_hostname_short'] }}"
      p_vmname:   "{{ g_clusterName }}-{{ hostvars[item]['inventory_hostname_short'] }}"
      p_mac:      "{{ hostvars[item]['h_pubMAC'] }}"
      p_ip:       "{{ hostvars[item]['h_pubIP'] }}"
      p_nm:       "{{ hostvars[item]['g_pubNM'] }}"
      p_gw:       "{{ hostvars[item]['g_pubGW'] }}"
      p_bus:      "{{ hw_profile[hostvars[item]['h_hwPROF']].disk.bus }}"
      p_dns:      "{{ hostvars[item]['g_pubDNS'] }}"
      p_sparse:   "{{ hw_profile[hostvars[item]['h_hwPROF']].disk.sparse }}"
      p_netdev:   "{{ hw_profile[hostvars[item]['h_hwPROF']].network.model }}"
      p_disksize: "{{ rs_profile[hostvars[item]['h_rsPROF']].disksize }}"
      p_memsize:  "{{ rs_profile[hostvars[item]['h_rsPROF']].memsize }}"
      p_cpu:      "{{ rs_profile[hostvars[item]['h_rsPROF']].vcpus }}"
    shell:
      cmd: |
        virt-install --name="{{ p_vmname }}" \
                     --ram="{{ p_memsize }}" \
                     --disk "{{ kvm_cfg.qcow_dir }}/{{ p_vmname }}.qcow2,bus={{ p_bus }},sparse={{ p_sparse }},size={{ p_disksize }}" \
                     --check disk_size=off \
                     --location={{ kvm_cfg.iso.dir }}/{{ kvm_cfg.iso.name }} \
                     --extra-args="ks={{ kvm_cfg.ks_url }} ip={{ p_ip }} netmask={{ p_nm }} dns={{ p_dns }} gateway={{ p_gw }}" \
                     --network "network={{ kvm_cfg.network.name }},mac={{ p_mac }},model={{ p_netdev }}" \
                     --graphics vnc \
                     --vcpus {{ p_cpu }} \
                     --boot hd,network,menu=yes \
                     --noautoconsole
    loop: "{{ groups['myNodes'] }}"

  - name: "LIBVIRT-CREATE-BASTION: give nodes a chance to install and reboot"
    vars:
      p_vmname:   "{{ g_clusterName }}-{{ hostvars[item]['inventory_hostname_short'] }}"
    shell:
      cmd: |
        virsh domstate "{{ p_vmname }}" | grep -q "shut off"
    register: result
    until:  result.rc == 0
    retries: 600
    delay: 5
    loop: "{{ groups['myNodes'] }}"

  - name: "LIBVIRT-CREATE-NODE: inject ssh key to node vm"
    vars:
      p_vmname:   "{{ g_clusterName }}-{{ hostvars[item]['inventory_hostname_short'] }}"
    shell:
      cmd: |
        virt-customize -d "{{ p_vmname }}" \
                       --ssh-inject root:file:/root/.ssh/id_rsa.pub \
                       --selinux-relabel
    loop: "{{ groups['myNodes'] }}"

  - name: "LIBVIRT-CREATE-NODE: start node vm"
    vars:
      p_vmname:   "{{ g_clusterName }}-{{ hostvars[item]['inventory_hostname_short'] }}"
    shell:
      cmd: |
        virsh start "{{ p_vmname }}"
    loop: "{{ groups['myNodes'] }}"

  - name: "LIBVIRT-CREATE-NODE: give node a chance to boot"
    wait_for:
      host: "{{ hostvars[item]['h_pubIP'] }}"
      connect_timeout: 5
      delay: 15
      port: 22
      sleep: 1
      state: started
      timeout: 300
    loop: "{{ groups['myNodes'] }}"

  - name: "LIBVIRT-CREATE-NODE: clean out local ssh keys for node"
    shell:
      cmd: |
        ssh-keygen -R "{{ hostvars[item]['inventory_hostname'] }}"
        ssh-keygen -R "{{ hostvars[item]['inventory_hostname_short'] }}"
        ssh-keygen -R "{{ hostvars[item]['inventory_hostname_short'] }}.{{ g_clusterName }}.{{ g_publicDomain }}"
        ssh-keygen -R "{{ hostvars[item]['h_pubIP'] }}"
    loop: "{{ groups['myNodes'] }}"
    ignore_errors: yes

  - name: "LIBVIRT-CREATE-NODE: add ssh keys for node"
    vars:
      p_fqdn:   "{{ hostvars[item]['inventory_hostname_short'] }}.{{ g_pubFQDN }}"
    shell:
      cmd: |
        ssh-keyscan "{{ p_fqdn }}" >> /root/.ssh/known_hosts
    loop: "{{ groups['myNodes'] }}"

