## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##   This loop iterates over the (sorted) deployer_plan.passes
##   and then includes the libvirt-deploy-taskblocks to run deployment
##   plays on the defined hostgroup
##
##   A deploy_plan pass is aligned 1-to-1 with a ansible hostgroup
##   All hosts in deploy_plan pass use an identical deployment strategy
##

---
- hosts: myVirthost

  tasks:

  ##
  ## Combine DEFAULT with LOCAL profile configs into single dictionaries
  ## 

  - set_fact: rs_profile="{{ rs_profile | combine(local_rs_profile) }}"
    when: local_rs_profile is defined

  - set_fact: ks_profile="{{ ks_profile | combine(local_ks_profile) }}"
    when: local_ks_profile is defined

  - set_fact: hw_profile="{{ hw_profile | combine(local_hw_profile) }}"
    when: local_hw_profile is defined

  ##
  ## Create QCOW directory if needed
  ##

  - name: "LIBVIRT-DEPLOY: Create qcow directory"
    file:
      path: "{{ kvm_cfg.qcow_dir }}"
      mode: "0775"
      state: directory

  ##
  ## Pre-Deploy / Deploy / Post-Deploy
  ##

  - name: "LIBVIRT-DEPLOY:  Deployer-plan pre-install ({{ deployer_plan.pre_install }})'"
    shell: "cd .. ; {{ deployer_plan.pre_install }}"
    when: deployer_plan.pre_install != ""

  - name: "LIBVIRT-DEPLOY: Deployer-plan pass iteration (invoke taskblock-hostgroup)"
    include_tasks: libvirt-deploy-taskblock-hostgroup.yml
    loop: "{{ deployer_plan['passes'] | flatten(1) | sort }}"
    when: deployer_plan.passes[item]['hostgroup'] != ""

  - name: "LIBVIRT-DEPLOY: Deployer-plan post-install ({{ deployer_plan.post_install }})'"
    shell: "cd .. ; {{ deployer_plan.post_install }}"
    when: deployer_plan.post_install != ""

