## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   This playbook attempts to configure a rhel 8.0 (or later) system with libvirt
##   to host an openshift 4.2 deployment
##
##   This playbook is NOT meant for student execution  
##
##   This playbook IS meant for someone who'd like to stand up Openshift on a single node
##
## Playbook Assumptions:
##     #1 you are executing this on the OS already installed on bare-metal
##     #2 your host is registered to RH CDN with subscription-manager
##     #3 the following packages have been installed: git, ansible
##     #4 system has plenty of storage and memory
##

---
- hosts: myVirthost

  tasks:

  - debug:
      msg: "Ansible Facts: {{ ansible_distribution }} {{ ansible_distribution_major_version  }}"

  - name: "LIBVIRT-SETUP: Create qcow directory"
    file:
      path: "{{ kvm_cfg.qcow_dir }}"
      mode: "0775"
      state: directory

  - block:

      - name: "LIBVIRT-SETUP: Subscription Manager enable RHEL 7 required repos only"
        rhsm_repository: 
          name: "rhel-7-server-rpms,rhel-7-server-optional-rpms,rhel-7-server-extras-rpms"
          purge: True
          state: enabled

      - name: "LIBVIRT-SETUP: Install python"
        yum: name=python state=installed

    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "7"

  - block:

      - name: "LIBVIRT-SETUP: Subscription Manager enable RHEL 8 required repos only"
        rhsm_repository: 
          name: "rhel-8-for-x86_64-baseos-rpms,rhel-8-for-x86_64-appstream-rpms"
          purge: True
          state: enabled

      - name: "LIBVIRT-SETUP: Install python"
        yum: name=python3 state=installed

      - name: "LIBVIRT-SETUP: Configure python3 alternatives"
        alternatives:
           name='python'
           link='/bin/python3'
           path='/bin/python'

    when:
      - ansible_distribution == "RedHat"
      - ansible_distribution_major_version == "8"

  - name: "LIBVIRT-SETUP: Install virtualization packages"
    yum: name=qemu-kvm,libvirt,virt-install,libvirt-client,libguestfs-tools state=installed
