## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   Populate /etc/hosts with entries from our cluster
##
## Playbook Assumptions:
##

---
- hosts: myVirthost
  tasks:

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_libvirt }}"

  ## Put entry in /etc/hosts so virthost and clients (via dnsmasq) can resolv

  - name: "LIBVIRT-DNS: update /etc/hosts"
    lineinfile: 
      dest:   "/etc/hosts"
      regexp: ".*{{ item }}$" 
      line:   "{{ hostvars[item]['h_pubIP'] }} {{item}}.{{g_pubFQDN}} {{item}}"
      state:  present
    when: hostvars[item]['h_pubIP'] is defined
    loop: "{{ groups['all'] }}"

  ## dnsmasq is controlled by libvirt, so using systemctl is pointless

  - name: "LIBVIRT-DNS: sigup dnsmasq"
    shell:
      cmd: |
        pkill -hup dnsmasq
