########################################
##
## Reference
##
##   https://www.linuxtechi.com/enable-nested-virtualization-kvm-centos-7-rhel-7/

---
- hosts: myVirthost
  tasks:

########################################
##
## Test for hardware compatability
##

  - name: "LIBVIRT-NESTED-VIRT: hardware check"
    shell:
      cmd: |
        grep -q -E 'svm|vmx' /proc/cpuinfo

########################################
##
## For now, only working with INTEL
##
## cat /sys/module/kvm_intel/parameters/nested
##  OR
## cat /sys/module/kvm_amd/parameters/nested

  - name: "LIBVIRT-NESTED-VIRT: check if nested virt enabled"
    shell:
      cmd: |
        grep -q 'Y' /sys/module/kvm_intel/parameters/nested
    register: test_nestedvirt

########################################
##
## Deploy configuration template
##

  - name: "LIBVIRT-NESTED-VIRT: deploy config template"
    when: test_nestedvirt.rc != 0
    template:
      src:  nested-virt-intel.j2
      dest: /etc/modprobe.d/kvm-nested.conf
      mode: 0644

########################################
##
## Reload the kernel module
##

  - name: "LIBVIRT-NESTED-VIRT: stop libvirtd service"
    when: test_nestedvirt.rc != 0
    service:
      name: libvirtd
      state: stopped

  - name: "LIBVIRT-NESTED-VIRT: check if nested virt enabled"
    when: test_nestedvirt.rc != 0
    shell:
      cmd: |
        modprobe -r kvm_intel
        sleep 3
        modprobe -a kvm_intel

  - name: "LIBVIRT-NESTED-VIRT: start libvirtd service"
    when: test_nestedvirt.rc != 0
    service:
      name: libvirtd
      state: started

########################################
##
## FIN!
##

