## Authors: 
##   Christoph Doerbeck
##
## Summary:
##   Populate /etc/hosts with entries from our cluster
##
## Playbook Assumptions:
##

---
- hosts: myVirthost
  tasks:

  - name: "LIBVIRT-DNS: cleanup conflicting IPs in /etc/hosts"
    lineinfile: 
      dest:   "/etc/hosts"
      regexp: "{{ hostvars[item]['h_pubIP'] }} .*$" 
      state:  absent
    when: hostvars[item]['h_pubIP'] is defined
    loop: "{{ groups['all'] }}"

  - name: "LIBVIRT-DNS: cleanup conflicting names in /etc/hosts"
    lineinfile: 
      dest:   "/etc/hosts"
      regexp: ".*{{ item }}.{{ g_pubFQDN }}.*" 
      state:  absent
    when: hostvars[item]['h_pubIP'] is defined
    loop: "{{ groups['all'] }}"

  - name: "LIBVIRT-DNS: add entries in /etc/hosts"
    lineinfile: 
      dest:   "/etc/hosts"
      line:   "{{ hostvars[item]['h_pubIP'] }} {{ item }}.{{ g_pubFQDN }}"
      state:  present
    when: hostvars[item]['h_pubIP'] is defined
    loop: "{{ groups['all'] }}"

  ## dnsmasq is controlled by libvirt, so using systemctl is pointless

  - name: "LIBVIRT-DNS: sig-hup dnsmasq"
    shell:
      cmd: |
        pkill -hup dnsmasq
