## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##   This loop iterates over the (sorted) kvm_deploy_plan.passes
##   and then includes the task-undeploy.yml to run un-deployment
##   plays on the defined hostgroup
##
##   A deploy_plan pass is aligned 1-to-1 with a ansible hostgroup
##   All hosts in deploy_plan pass use an identical deployment strategy
##

---
- hosts: myVirthost

  tasks:

##
## Delete VMs (domains)
##

  - name: "LIBVIRT-UNDEPLOY: Iterating over passes"
    include_tasks: tasks-undeploy.yml
    loop: "{{ kvm_deploy_plan['passes'] | flatten(1) | sort }}"
    when: kvm_deploy_plan.passes[item]['hostgroup'] != ""

##
## Delete Network
##

  - name: "LIBVIRT-UNDEPLOY: test existence of libvirt network ({{ kvm_cfg.network.name }})"
    shell: 
      cmd: |
        virsh net-info "{{ kvm_cfg.network.name }}"
    ignore_errors: yes
    register: test_libvirt_network

  - debug: msg="Libvirt Network Test Result Code = {{ test_libvirt_network.rc }}"



  - name: "LIBVIRT-UNDEPLOY: test existence of network bridge ({{ kvm_cfg.network.bridge }})"
    when: 
      - kvm_cfg.network.fwd_type == "bridge"
      - test_libvirt_network.rc == 0
    shell: 
      cmd: |
        nmcli dev show "{{ kvm_cfg.network.bridge }}"
    ignore_errors: yes
    register: test_bridge_network

  - debug: msg="Bridge Network Test Result Code = {{ test_bridge_network.rc }}"
    when: 
      - kvm_cfg.network.fwd_type == "bridge"
      - test_libvirt_network.rc == 0



  - name: "LIBVIRT-UNDEPLOY: undefine libvirt network ({{ kvm_cfg.network.name }})"
    when: test_libvirt_network.rc == 0
    shell:
      cmd: |
        virsh net-undefine {{ kvm_cfg.network.name }}

  - name: "LIBVIRT-UNDEPLOY: destroy libvirt network ({{ kvm_cfg.network.name }})"
    when: test_libvirt_network.rc == 0
    shell: 
      cmd: |
        virsh net-destroy {{ kvm_cfg.network.name }}


## Due to the complexities of bridging and "undoing" bridge without loosing network
## connectivity, I opt NOT to touch bridge and their interfaces
#  - name: "LIBVIRT-UNDEPLOY: remove device from bridge ({{ kvm_cfg.network.name }})"
#    when: 
#      - kvm_cfg.network.fwd_type == "bridge"
#      - test_libvirt_network.rc == 0 
#      - test_bridge_network.rc == 0
#    shell:
#      cmd: |
#        nmcli con delete type ethernet "{{ kvm_cfg.network.dev }}" 
#
#  - name: "LIBVIRT-UNDEPLOY: remove bridge device ({{ kvm_cfg.network.name }})"
#    when: 
#      - kvm_cfg.network.fwd_type == "bridge"
#      - test_libvirt_network.rc == 0 
#      - test_bridge_network.rc == 0
#    shell:
#      cmd: |
#        nmcli con delete type bridge "{{ kvm_cfg.network.bridge }}" 

