## Authors: 
##   Christoph Doerbeck
##
## Summary:
##

---
- hosts: localhost

  tasks:

  - debug:
      msg: "Ansible Facts: {{ ansible_distribution }} {{ ansible_distribution_major_version  }}"

  - name: "OVIRT-BASICS: install oVirt API"
    yum: name=python-ovirt-engine-sdk4 state=installed

