## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##
##

---
- hosts: myVirthost
  tasks:

  - debug:
      var: rs_profile[hostvars[item]['h_rsPROF']]
    loop: "{{ groups['myBastion'] }}"

  - debug:
      var: hw_profile[hostvars[item]['h_hwPROF']]
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: deploy kickstart configuration"
    vars:
      - p_diskDevice: "{{ hw_profile[hostvars[item]['h_hwPROF']].disk.dev }}"
    template:
      src: "ks-baseos.j2"
      dest: "/var/www/html/ks.cfg"
      owner: root
      group: apache
      mode: 0644
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: build virt-install scripts"
    include_tasks: tasks-build-virtinstall-scripts.yml
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: execute virt-install scripts"
    shell:
      cmd: |
        bash "/var/tmp/{{ item }}-virtinstall.sh"
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: give nodes a chance to install and shutdown"
    vars:
      p_vmname:   "{{ g_clusterName }}-{{ hostvars[item]['inventory_hostname_short'] }}"
    shell:
      cmd: |
        virsh domstate "{{ p_vmname }}" | grep -q "shut off"
    register: result
    until:  result.rc == 0
    retries: 600
    delay: 5
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: inject ssh key to bastion vm"
    vars:
      p_vmname:   "{{ g_clusterName }}-{{ hostvars[item]['inventory_hostname_short'] }}"
    shell:
      cmd: |
        virt-customize -d "{{ p_vmname }}" \
                       --ssh-inject root:file:/root/.ssh/id_rsa.pub \
                       --selinux-relabel
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: start bastion vm"
    vars:
      p_vmname:   "{{ g_clusterName }}-{{ hostvars[item]['inventory_hostname_short'] }}"
    shell:
      cmd: |
        virsh start "{{ p_vmname }}"
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: give bastion a chance to boot"
    wait_for:
      host: "{{ hostvars[item]['h_pubIP'] }}"
      connect_timeout: 5
      delay: 15
      port: 22
      sleep: 1
      state: started
      timeout: 300
    loop: "{{ groups['myBastion'] }}"

  - name: "LIBVIRT-CREATE-BASTION: clean out local ssh keys for bastion"
    shell:
      cmd: |
        ssh-keygen -R "{{ hostvars[item]['inventory_hostname'] }}"
        ssh-keygen -R "{{ hostvars[item]['inventory_hostname_short'] }}"
        ssh-keygen -R "{{ hostvars[item]['inventory_hostname_short'] }}.{{ g_clusterName }}.{{ g_publicDomain }}"
        ssh-keygen -R "{{ hostvars[item]['h_pubIP'] }}"
    loop: "{{ groups['myBastion'] }}"
    ignore_errors: yes

  - name: "LIBVIRT-CREATE-BASTION: add ssh keys for bastion"
    vars:
      p_fqdn:   "{{ hostvars[item]['inventory_hostname_short'] }}.{{ g_pubFQDN }}"
    shell:
      cmd: |
        ssh-keyscan "{{ p_fqdn }}" >> /root/.ssh/known_hosts
    loop: "{{ groups['myBastion'] }}"

