
hw_profile:

  default:
    description: "Default system hardware profile"
    disk:
      dev:    "sda"

  kvm_vda:
    description: "KVM based virtual machine using disk.bus = virtio"
    platform: "libvirt"
    disk:
      bus:    "virtio"
      sparse: "true"
      dev:    "vda"
    network:
      model:  "virtio"

  kvm_nest_vda:
    description: "KVM based virtual machine with nested-virt and disk.bus = virtio"
    platform: "libvirt"
    cpu:
      type:   "host-passthrough"
    disk:
      bus:    "virtio"
      sparse: "true"
      dev:    "vda"
    network:
      model:  "virtio"

  kvm_sda:
    description: "KVM based virtual machine using disk.bus = virtio-scsi"
    platform: "libvirt"
    disk:
      bus:    "virtio-scsi"
      sparse: "true"
      dev:    "sda"
    network:
      model:  "virtio"

  ovirt_sda:
    description: "oVirt based virtual machine using disk.bus = virtio-scsi (sda)"
    platform: "ovirt"
    disk:
      bus:    "virtio_scsi"
      sparse: "true"
      dev:    "sda"
    network:
      model:  "virtio"
      profile: "ovirtmgmt"

  ovirt_vda:
    description: "oVirt based virtual machine using disk.bus = virtio (vda)"
    platform: "ovirt"
    disk:
      bus:    "virtio"
      sparse: "true"
      dev:    "vda"
    network:
      model:  "virtio"
      profile: "ovirtmgmt"

  vmware_sda:
    description: "VMWare based virtual machine using disk.bus = TBD"
    disk:
      dev:    "sda"

  dell_r720:
    description: "DELL r710 example"
    disk:
      dev:    "sda"

  hp_dl380:
    description: "HP DL380"
    usb_delay: "10"
    disk:
      dev:    "sda"
