
ks_profile:

  rhel8_lvm:

    ## ISO needs to be located at      kvm_cfg.iso.dir
    ## ISO will be loopback mounted at kvm_cfg.ks_url/mnt
    ## repos will be configured on     kvm_cfg.ks_url/mnt/path

    template:   "ks-rhel8-lvm.j2"
    iso:        "rhel-8.2-x86_64-dvd.iso"
    mnt:        "rhel-8.2"
    repos:
      repo1 :
        name:   "rhel-8-baseos-rpms"
        path:   "BaseOS"
      repo2 :
        name:   "rhel-8-appstream-rpms"
        path:   "AppStream"

  rhel82_lvm:

    template:   "ks-rhel8-lvm.j2"
    iso:        "rhel-8.2-x86_64-dvd.iso"
    mnt:        "rhel-8.2"
    repos:
      repo1 :
        name:   "rhel-8-baseos-rpms"
        path:   "BaseOS"
      repo2 :
        name:   "rhel-8-appstream-rpms"
 
  rhel81_lvm:

    template:   "ks-rhel8-lvm.j2"
    iso:        "rhel-8.1-x86_64-dvd.iso"
    mnt:        "rhel-8.1"
    repos:
      repo1 :
        name:   "rhel-8-baseos-rpms"
        path:   "BaseOS"
      repo2 :
        name:   "rhel-8-appstream-rpms"
        path:   "AppStream"

  rhel7_lvm:

    template:   "ks-rhel7-lvm.j2"
    iso:        "rhel-server-7.8-x86_64-dvd.iso"
    mnt:        "rhel-7.8"
    repos:
      repo1 :
        name:   "rhel-7-server-rpms"
        path:   ""

  rhel76_lvm:

    template:   "ks-rhel7-lvm.j2"
    iso:        "rhel-server-7.6-x86_64-dvd.iso"
    mnt:        "rhel-7.6"
    repos:
      repo1 :
        name:   "rhel-7-server-rpms"
        path:   ""
