## Authors: 
##   Christoph Doerbeck
##
## Summary:
##
##   TBD 

---
- hosts: myBastion
  tasks:

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_libvirt }}"

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_rs_profiles }}"

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_hw_profiles }}"

  - debug:
      var: kvm_cfg.repo[item]
    with_items: "{{ kvm_cfg.repo }}"

  - debug:
      var: kvm_cfg.repo[item].name
    with_items: "{{ kvm_cfg.repo }}"

  - name: Add repository
    yum_repository:
      name:        "{{ kvm_cfg.repo[item].name }}"
      description: "{{ kvm_cfg.repo[item].name }}"
      baseurl:     "{{ kvm_cfg.repo[item].url }}"
      enabled:     "yes"
      gpgcheck:    "no"
    with_items: "{{ kvm_cfg.repo }}"





- hosts: myVirthost
  tasks:

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_libvirt }}"

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_rs_profiles }}"

  - include_vars: "{{ item }}"
    with_first_found: "{{ vars_hw_profiles }}"

  - name: "LIBVIRT-REPOSYNC: loopback mount ISO"
    mount:
      src:    "{{ kvm_cfg.iso.dir }}/{{ kvm_cfg.iso.name }}"
      path:   "{{ kvm_cfg.iso.mount }}"
      opts:   "loop,ro"
      state:  "mounted"
      fstype: "iso9660"
