
##
## Virtual Machine Parameters (libvirt)
##
##   these are the documented minimums for Openshift 4.3
##   diskbus: virtio        - will produce vms using /dev/vda
##   diskbus: virtio-scsi   - will produce vms using /dev/sda
##
## WARNING:
##
##   Since this typically for Proof-of-Concept or simply education, we
##   also use 'sparse' disks.  If this has a chance of running longer than
##   a few days, change "sparse: false".  You'll get better performance
##   and things won't blow up when space runs out.
##

## ------------------------------
## KVM/Libvirt Config Options

g_http_port:    "8008"
g_cockpit_port: "9090"


kvm_cfg: 

  http_port:    "{{ g_http_port }}"
  cockpit_port: "{{ g_cockpit_port }}"

  qcow_dir:     "/home/virt-images"

  ks_url:       "http://{{ ansible_default_ipv4.address }}:{{ g_http_port }}/ks.cfg"

  network:
    name:       "virbr-{{ g_clusterName }}"
    bridge:     "virbr-{{ g_clusterName }}"
    fwd_type:   "bridge"
    dev:        "eno1"
    ipv4:
      addr:     "192.168.1.22/{{ g_pubPREFIX }}"
      gw:       "{{ g_pubNM }}"

  iso:
    dir:        "/var/www/html/iso"
    name:       "rhel-8.1-x86_64-dvd.iso"
    mount:      "/var/www/html/repo"

  repo:
    repo1 :
      name: "rhel-8-baseos-rpms"
      url:  "http://{{ ansible_default_ipv4.address }}:{{ g_http_port }}/repo/BaseOS"
    repo2 :
      name: "rhel-8-appstream-rpms"
      url:  "http://{{ ansible_default_ipv4.address }}:{{ g_http_port }}/repo/AppStream"

